CREATE DATABASE LIVRARIA;
USE LIVRARIA;

CREATE TABLE CADASTRO(
CODIGO INT PRIMARY KEY, 
USUARIO VARCHAR (10), 
SENHA VARCHAR (15)
);

CREATE TABLE AUTOR(
CODIGO INT PRIMARY KEY,
NOME VARCHAR(50)
);
CREATE TABLE TITULO(
CODIGO INT PRIMARY KEY,
NOME VARCHAR(100)
);
CREATE TABLE CATEGORIA(
CODIGO INT PRIMARY KEY,
NOME_CATEGORA VARCHAR(30)
); 

